In [1]:
from flask import Flask

In [ ]:
'''
#intilization of flask
#reg = LinearRegression()
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello Everyone in the first session of Deployment"

If__name__=="__main__":
    app.run()
    
'''

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

c:\users\akash\appdata\local\programs\python\python36\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [3]:
import pickle

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/main/hiring.csv")

In [6]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [7]:
df.isna().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [8]:
df['experience'].fillna(0,inplace =True)

In [9]:
df.isna().sum()

experience         0
test_score         1
interview_score    0
salary             0
dtype: int64

In [10]:
df['test_score'].fillna(df.test_score.mean(),inplace=True)

In [11]:
df.isna().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

# Dataset cleaning is done now


In [12]:
df

experience  test_score  interview_score  salary
0          0    8.000000                9   50000
1          0    8.000000                6   45000
2       five    6.000000                7   60000
3        two   10.000000               10   65000
4      seven    9.000000                6   70000
5      three    7.000000               10   62000
6        ten    7.857143                7   72000
7     eleven    7.000000                8   80000

In [13]:
X= df.iloc[:,:-1]

In [14]:
X.shape

(8, 3)

In [15]:
X.head()

experience  test_score  interview_score
0          0         8.0                9
1          0         8.0                6
2       five         6.0                7
3        two        10.0               10
4      seven         9.0                6

In [16]:
X.experience.unique()

array([0, 'five', 'two', 'seven', 'three', 'ten', 'eleven'], dtype=object)

In [20]:
def conv_dict(x):
    dict = {
        'five':5,
        'two':2,
        'seven':7,
        'three':3,
        'ten':10,
        'eleven':11,
        0:0
    }
    return dict[x]

In [21]:
conv_dict('three')

3

In [22]:
X.experience = X.experience.apply(conv_dict)

In [23]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [24]:
y = df.iloc[:,-1]

In [25]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

# I am not going to do train and test split 
## However, you all are encouraged to do it later 

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
lr = LinearRegression()

In [28]:
lr.fit(X,y)

LinearRegression()

In [29]:
y_pred = lr.predict(X)
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [30]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [31]:
#unseen Data
lr.predict([[3,9,7]])

array([58315.5019167])

# Model Deployment

In [32]:
#import pickle
pickle.dump(lr,open('lr_model.pkl','wb'))
# Dump will save your model in the given name('lr_model.pkl') in your ssd/hdd
#this file is writte in "write bytes mode"

In [34]:
vishal = pickle.load(open("lr_model.pkl","rb"))
vishal

LinearRegression()

In [36]:
lr.predict([[10,10,10]])

array([86612.80419155])